---
title: "Scraping the text data"
author: "Al Ashir Intisar"
date: "4/26/2023"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***Necessary Library***

```{r}
library(tidyverse)
library(rvest)
library(robotstxt)
```


***Function to scrape the data***

```{r}
scrape_ep <- function(ep_url){
  robotstxt::paths_allowed(ep_url) 
  
  # content <- read_html(ep_url) %>%
  #   html_nodes(".content") %>%
  #   html_text()


  # speakers <- regmatches(content, gregexpr("\\w[A-Z]+:", content))|>
  #   unlist()
  # speakers <- gsub(":", "", speakers)
  # 

  show_title <- read_html(ep_url) %>%
    html_nodes("#mw-pages .mw-category-group a") %>%
    html_text()
  
  decade <- read_html(ep_url)|>
    html_nodes("b")|>
    html_text()

  tibble(title =show_title,  decade = decade)
  
}
```


***url for sitcom lists from wikipedia***

```{r}
url_1940 <- "https://en.wikipedia.org/wiki/Category:1940s_American_sitcoms"
sitcoms_1940s <- scrape_ep(url_1940)

url_1950 <- "https://en.wikipedia.org/wiki/Category:1950s_American_sitcoms"
sitcoms_1950s <- scrape_ep(url_1950)

url_1960 <- "https://en.wikipedia.org/wiki/Category:1960s_American_sitcoms"
sitcoms_1960s <- scrape_ep(url_1960)

url_1970 <- "https://en.wikipedia.org/wiki/Category:1970s_American_sitcoms"
sitcoms_1970s <- scrape_ep(url_1970)

url_1980 <- "https://en.wikipedia.org/wiki/Category:1980s_American_sitcoms"
sitcoms_1980s <- scrape_ep(url_1980)

url_1990 <- "https://en.wikipedia.org/wiki/Category:1990s_American_sitcoms"
sitcoms_1990s <- scrape_ep(url_1990)

url_2000 <- "https://en.wikipedia.org/wiki/Category:2000s_American_sitcoms"
sitcoms_2000s <- scrape_ep(url_2000)

url_2010 <- "https://en.wikipedia.org/wiki/Category:2010s_American_sitcoms"
sitcoms_2010s <- scrape_ep(url_2010)

url_2020 <- "https://en.wikipedia.org/wiki/Category:2020s_American_sitcoms"
sitcoms_2020s <- scrape_ep(url_2020)

```


```{r}
Sitcom_list <- rbind(sitcoms_1940s, sitcoms_1950s, sitcoms_1960s, sitcoms_1970s, sitcoms_1980s, sitcoms_1990s, sitcoms_2000s, 
                     sitcoms_2010s, sitcoms_2020s)
Sitcom_list <- Sitcom_list|>
  mutate(decade = parse_number(decade))

write_csv(Sitcom_list, "~/ADM_MSCS_341/ADM_MSCS_341/Spotlight/sitcom_list.csv")
```

